/**
 * French names for the movement library.
 *
 * The built-in movements and everything imported from Hevy arrive with Hevy's
 * English names. The coach works in French, and so does her client: this is
 * the name shown in the library and the one written into a session when a
 * movement is added to a day. The English name stays in the exercises table,
 * so a later Hevy import still recognises what it already brought in.
 *
 * Gym French, not dictionary French: "Hip thrust" and "Leg extension" stay as
 * coaches say them.
 */
const FR: Record<string, string> = {
  "21s Bicep Curl": "Curl biceps 21",
  "Ab Scissors": "Ciseaux abdominaux",
  "Ab Wheel": "Roue abdominale",
  "Ab Wheel Rollout": "Roue abdominale (déroulé)",
  "Aerobics": "Aérobic",
  "Air Bike": "Air bike",
  "Arnold Press": "Développé Arnold",
  "Around The World": "Tour du monde",
  "Assault Bike": "Assault bike",
  "Assisted Pistol Squats": "Pistol squat assisté",
  "Back Extension": "Extension lombaire",
  "Back Extension (Hyperextension)": "Hyperextension",
  "Back Extension (Weighted Hyperextension)": "Hyperextension lestée",
  "Back Squat": "Squat arrière",
  "Ball Slams": "Slam ball",
  "Band Pullaparts": "Écartés à l’élastique",
  "Barbell Curl": "Curl à la barre",
  "Barbell Row": "Rowing barre",
  "Battle Ropes": "Cordes ondulatoires",
  "Bear Crawl": "Marche de l’ours",
  "Behind the Back Curl (Cable)": "Curl derrière le dos (poulie)",
  "Behind the Back Wrist Curl": "Curl poignets derrière le dos",
  "Belt Squat": "Belt squat",
  "Bench Dip": "Dips sur banc",
  "Bench Press": "Développé couché",
  "Bench Press (Cable)": "Développé couché (poulie)",
  "Bench Press (Smith Machine)": "Développé couché (Smith)",
  "Bench Press - Close Grip": "Développé couché prise serrée",
  "Bench Press - Wide Grip": "Développé couché prise large",
  "Bent Over Row": "Rowing buste penché",
  "Bent Over Row (Band)": "Rowing buste penché (élastique)",
  "Bent Over Row (Smith Machine)": "Rowing buste penché (Smith)",
  "Bicep Curl": "Curl biceps",
  "Bicep Curl (Cable)": "Curl biceps (poulie)",
  "Bicycle Crunch": "Crunch vélo",
  "Bicycle Crunch Raised Legs": "Crunch vélo jambes levées",
  "Bird Dog": "Bird dog",
  "Box Jump": "Saut sur box",
  "Box Squat": "Squat sur box",
  "Boxing": "Boxe",
  "Bulgarian Split Squat": "Squat bulgare",
  "Burpee": "Burpee",
  "Burpee Broad Jumps": "Burpee saut en longueur",
  "Burpee Over the Bar": "Burpee par-dessus la barre",
  "Butterfly (Pec Deck)": "Butterfly (pec deck)",
  "Cable Core Pallof Press": "Pallof press (poulie)",
  "Cable Crunch": "Crunch à la poulie",
  "Cable Curl": "Curl à la poulie",
  "Cable Fly": "Écarté à la poulie",
  "Cable Fly Crossovers": "Vis-à-vis à la poulie",
  "Cable Lateral Raise": "Élévation latérale à la poulie",
  "Cable Pull Through": "Pull through à la poulie",
  "Cable Twist (Down to up)": "Rotation à la poulie (bas vers haut)",
  "Cable Twist (Up to down)": "Rotation à la poulie (haut vers bas)",
  "Calf Extension": "Extension des mollets",
  "Calf Press": "Mollets à la presse",
  "Chest Dip": "Dips pectoraux",
  "Chest Dip (Assisted)": "Dips pectoraux (assisté)",
  "Chest Dip (Weighted)": "Dips pectoraux (lesté)",
  "Chest Fly": "Écarté pectoraux",
  "Chest Fly (Band)": "Écarté pectoraux (élastique)",
  "Chest Press": "Presse pectoraux",
  "Chest Press (Band)": "Presse pectoraux (élastique)",
  "Chest Press (Plates)": "Presse pectoraux (disques)",
  "Chest Supported Incline Row": "Rowing incliné appui pectoral",
  "Chest Supported Reverse Fly": "Oiseau appui pectoral",
  "Chest Supported T Bar Row": "Rowing T-bar appui pectoral",
  "Chest Supported Y Raise": "Élévation en Y appui pectoral",
  "Chest-Supported Row": "Rowing appui pectoral",
  "Chin Up": "Traction supination",
  "Chin Up (Assisted)": "Traction supination (assistée)",
  "Chin Up (Weighted)": "Traction supination (lestée)",
  "Chin-Up": "Traction supination",
  "Clamshell": "Clamshell",
  "Clap Push Ups": "Pompes claquées",
  "Clean": "Épaulé",
  "Clean Pull": "Tirage d’épaulé",
  "Clean and Jerk": "Épaulé-jeté",
  "Clean and Press": "Épaulé-développé",
  "Climbing": "Escalade",
  "Close-Grip Bench Press": "Développé couché prise serrée",
  "Concentration Curl": "Curl concentré",
  "Conventional Deadlift": "Soulevé de terre classique",
  "Cross Body Hammer Curl": "Curl marteau croisé",
  "Crunch": "Crunch",
  "Crunch (Weighted)": "Crunch (lesté)",
  "Curtsy Lunge": "Fente croisée",
  "Cycling": "Vélo",
  "Dead Bug": "Dead bug",
  "Dead Hang": "Suspension à la barre",
  "Deadlift": "Soulevé de terre",
  "Deadlift (Band)": "Soulevé de terre (élastique)",
  "Deadlift (Smith Machine)": "Soulevé de terre (Smith)",
  "Deadlift (Trap bar)": "Soulevé de terre (trap bar)",
  "Deadlift High Pull": "Soulevé de terre tirage haut",
  "Decline Bench Press": "Développé décliné",
  "Decline Bench Press (Smith Machine)": "Développé décliné (Smith)",
  "Decline Chest Fly": "Écarté décliné",
  "Decline Crunch": "Crunch décliné",
  "Decline Crunch (Weighted)": "Crunch décliné (lesté)",
  "Decline Push Up": "Pompes déclinées",
  "Deficit Deadlift": "Soulevé de terre en déficit",
  "Diamond Push Up": "Pompes diamant",
  "Dip": "Dips",
  "Downward Dog": "Chien tête en bas",
  "Drag Curl": "Drag curl",
  "Dragon Flag": "Dragon flag",
  "Dragonfly": "Dragonfly",
  "Dumbbell Bench Press": "Développé couché haltères",
  "Dumbbell Curl": "Curl haltères",
  "Dumbbell Overhead Extension": "Extension triceps haltère au-dessus de la tête",
  "Dumbbell Row": "Rowing haltère",
  "Dumbbell Snatch": "Arraché haltère",
  "Dumbbell Squeeze Press": "Squeeze press haltères",
  "Dumbbell Step Up": "Step-up haltères",
  "EZ Bar Biceps Curl": "Curl biceps barre EZ",
  "EZ-Bar Curl": "Curl barre EZ",
  "Elbow to Knee": "Coude au genou",
  "Elliptical Trainer": "Vélo elliptique",
  "Face Pull": "Face pull",
  "Farmer Carry": "Marche du fermier",
  "Farmers Walk": "Marche du fermier",
  "Feet Up Bench Press": "Développé couché pieds levés",
  "Fire Hydrants": "Fire hydrants",
  "Floor Press": "Développé au sol",
  "Floor Triceps Dip": "Dips triceps au sol",
  "Flutter Kicks": "Battements de jambes",
  "Forearm Extension": "Extension des avant-bras",
  "Frog Jumps": "Sauts de grenouille",
  "Frog Pumps": "Frog pumps",
  "Front Lever Hold": "Front lever (maintien)",
  "Front Lever Raise": "Front lever (montée)",
  "Front Raise": "Élévation frontale",
  "Front Raise (Band)": "Élévation frontale (élastique)",
  "Front Raise (Cable)": "Élévation frontale (poulie)",
  "Front Squat": "Squat avant",
  "Full Squat": "Squat complet",
  "Glute Bridge": "Pont fessier",
  "Glute Ham Raise": "Glute ham raise",
  "Glute Ham Raise Weighted": "Glute ham raise lesté",
  "Glute Kickback": "Kickback fessier",
  "Glute Kickback on Floor": "Kickback fessier au sol",
  "Goblet Squat": "Goblet squat",
  "Good Morning": "Good morning",
  "Gorilla Row": "Gorilla row",
  "HIIT": "HIIT",
  "HS Bicep Curl": "Curl biceps (Hammer Strength)",
  "HS Triceps Extension": "Extension triceps (Hammer Strength)",
  "Hack Squat": "Hack squat",
  "Hammer Curl": "Curl marteau",
  "Hammer Curl (Band)": "Curl marteau (élastique)",
  "Hammer Curl (Cable)": "Curl marteau (poulie)",
  "Handstand Hold": "Équilibre sur les mains",
  "Handstand Push Up": "Pompes en équilibre",
  "Hang Clean": "Épaulé en suspension",
  "Hang Snatch": "Arraché en suspension",
  "Hanging Knee Raise": "Relevé de genoux suspendu",
  "Hanging Leg Raise": "Relevé de jambes suspendu",
  "Heel Taps": "Touches talons",
  "Hex Press": "Hex press",
  "High Knee Skips": "Montées de genoux sautées",
  "High Knees": "Montées de genoux",
  "Hiking": "Randonnée",
  "Hip Abduction": "Abduction de hanche",
  "Hip Abduction (Cable)": "Abduction de hanche (poulie)",
  "Hip Adduction": "Adduction de hanche",
  "Hip Adduction (Cable)": "Adduction de hanche (poulie)",
  "Hip Thrust": "Hip thrust",
  "Hip Thrust (Smith Machine)": "Hip thrust (Smith)",
  "Hollow Rock": "Hollow rock",
  "Incline Bench Press": "Développé incliné",
  "Incline Bench Press (Smith Machine)": "Développé incliné (Smith)",
  "Incline Chest Butterfly (Machine Plate)": "Butterfly incliné (machine à disques)",
  "Incline Chest Fly": "Écarté incliné",
  "Incline Chest Press": "Presse pectoraux inclinée",
  "Incline Dumbbell Curl": "Curl incliné haltères",
  "Incline Dumbbell Press": "Développé incliné haltères",
  "Incline Push Ups": "Pompes inclinées",
  "Incline Treadmill Walk": "Marche inclinée sur tapis",
  "Inverted Row": "Rowing inversé",
  "Iso-Lateral Chest Press": "Presse pectoraux iso-latérale",
  "Iso-Lateral High Row": "Rowing haut iso-latéral",
  "Iso-Lateral Low Row": "Rowing bas iso-latéral",
  "Iso-Lateral Row": "Rowing iso-latéral",
  "Iso-lateral Horizontal Bench Press (machine Plates)": "Développé horizontal iso-latéral (machine à disques)",
  "Iso-lateral Incline Chest Press (machine Plate)": "Presse pectoraux inclinée iso-latérale (machine à disques)",
  "Iso-lateral Leg Extension (Machine Plate)": "Leg extension iso-latéral (machine à disques)",
  "JM Press": "JM press",
  "Jack Knife": "Jackknife",
  "Jackknife Sit Up": "Relevé de buste en portefeuille",
  "Jump Rope": "Corde à sauter",
  "Jump Shrug": "Shrug sauté",
  "Jump Squat": "Squat sauté",
  "Jumping Jack": "Jumping jack",
  "Jumping Lunge": "Fentes sautées",
  "Kettlebell Around the World": "Tour du monde kettlebell",
  "Kettlebell Clean": "Épaulé kettlebell",
  "Kettlebell Curl": "Curl kettlebell",
  "Kettlebell Goblet Squat": "Goblet squat kettlebell",
  "Kettlebell Halo": "Halo kettlebell",
  "Kettlebell High Pull": "Tirage haut kettlebell",
  "Kettlebell Shoulder Press": "Développé épaule kettlebell",
  "Kettlebell Snatch": "Arraché kettlebell",
  "Kettlebell Swing": "Swing kettlebell",
  "Kettlebell Turkish Get Up": "Turkish get-up kettlebell",
  "Kipping Pull Up": "Traction kipping",
  "Knee Raise Parallel Bars": "Relevé de genoux aux barres parallèles",
  "Kneeling Pulldown (band)": "Tirage à genoux (élastique)",
  "Kneeling Push Up": "Pompes sur les genoux",
  "L-Sit Hold": "L-sit (maintien)",
  "Landmine 180": "Landmine 180",
  "Landmine Press": "Développé landmine",
  "Landmine Row": "Rowing landmine",
  "Landmine Squat and Press": "Squat et développé landmine",
  "Lat Pulldown": "Tirage vertical",
  "Lat Pulldown (Band)": "Tirage vertical (élastique)",
  "Lat Pulldown (Cable)": "Tirage vertical (poulie)",
  "Lat Pulldown (single arm)": "Tirage vertical (un bras)",
  "Lat Pulldown - Close Grip (Cable)": "Tirage vertical prise serrée (poulie)",
  "Lateral Band Walks": "Pas chassés à l’élastique",
  "Lateral Box Jump": "Saut latéral sur box",
  "Lateral Leg Raises": "Élévations latérales de jambe",
  "Lateral Lunge": "Fente latérale",
  "Lateral Raise": "Élévation latérale",
  "Lateral Raise (Band)": "Élévation latérale (élastique)",
  "Lateral Raise (Cable)": "Élévation latérale (poulie)",
  "Lateral Raise (Machine Plate)": "Élévation latérale (machine à disques)",
  "Lateral Squat": "Squat latéral",
  "Laying Lateral Raise": "Élévation latérale allongé",
  "Leg Extension": "Leg extension",
  "Leg Press": "Presse à cuisses",
  "Leg Press Horizontal": "Presse à cuisses horizontale",
  "Leg Raise Parallel Bars": "Relevé de jambes aux barres parallèles",
  "Low Cable Fly Crossovers": "Vis-à-vis poulie basse",
  "Low Row": "Rowing bas",
  "Lunge": "Fente",
  "Lying Knee Raise": "Relevé de genoux allongé",
  "Lying Leg Curl": "Leg curl allongé",
  "Lying Leg Raise": "Relevé de jambes allongé",
  "Lying Neck Curls": "Flexion de la nuque allongé",
  "Lying Neck Curls (Weighted)": "Flexion de la nuque allongé (lesté)",
  "Lying Neck Extension": "Extension de la nuque allongé",
  "Lying Neck Extension (Weighted)": "Extension de la nuque allongé (lesté)",
  "Machine Chest Press": "Presse pectoraux machine",
  "Meadows Rows": "Meadows row",
  "Mountain Climber": "Mountain climber",
  "Muscle Up": "Muscle-up",
  "Negative Pull Up": "Traction négative",
  "Neutral-Grip Pulldown": "Tirage vertical prise neutre",
  "Nordic Curl": "Nordic curl",
  "Nordic Hamstrings Curls": "Nordic ischio-jambiers",
  "Oblique Crunch": "Crunch oblique",
  "One Arm Push Up": "Pompe à un bras",
  "Overhead Cable Extension": "Extension triceps poulie au-dessus de la tête",
  "Overhead Curl (Cable)": "Curl poulie haute",
  "Overhead Dumbbell Lunge": "Fente haltère au-dessus de la tête",
  "Overhead Plate Raise": "Élévation du disque au-dessus de la tête",
  "Overhead Press": "Développé militaire",
  "Overhead Press (Smith Machine)": "Développé militaire (Smith)",
  "Overhead Squat": "Squat bras tendus",
  "Overhead Triceps Extension (Cable)": "Extension triceps au-dessus de la tête (poulie)",
  "Pallof Press": "Pallof press",
  "Partial Glute Bridge": "Pont fessier partiel",
  "Pause Squat": "Squat avec pause",
  "Peacher Curl (Machine plates)": "Curl pupitre (machine à disques)",
  "Pec Deck": "Pec deck",
  "Pendlay Row": "Rowing Pendlay",
  "Pendulum Squat": "Pendulum squat",
  "Pike Pushup": "Pompes pike",
  "Pilates": "Pilates",
  "Pinwheel Curl": "Curl croisé",
  "Pistol Squat": "Pistol squat",
  "Plank": "Gainage planche",
  "Plank Pushup": "Planche-pompe",
  "Plate Curl": "Curl au disque",
  "Plate Front Raise": "Élévation frontale au disque",
  "Plate Press": "Développé au disque",
  "Plate Squeeze (Svend Press)": "Svend press",
  "Power Clean": "Power clean",
  "Power Snatch": "Power snatch",
  "Preacher Curl": "Curl pupitre",
  "Press Under": "Press under",
  "Pull Up": "Traction",
  "Pull Up (Assisted)": "Traction (assistée)",
  "Pull Up (Band)": "Traction (élastique)",
  "Pull Up (Weighted)": "Traction (lestée)",
  "Pull-Up": "Traction",
  "Pullover": "Pull-over",
  "Push Press": "Push press",
  "Push Up": "Pompes",
  "Push Up (Weighted)": "Pompes (lestées)",
  "Push Up - Close Grip": "Pompes prise serrée",
  "Push-Up": "Pompes",
  "Rack Pull": "Rack pull",
  "Rear Delt Fly": "Oiseau",
  "Rear Delt Reverse Fly": "Oiseau inversé",
  "Rear Delt Reverse Fly (Cable)": "Oiseau inversé (poulie)",
  "Rear Kick": "Kick arrière",
  "Recumbent Bike": "Vélo semi-allongé",
  "Renegade Row": "Renegade row",
  "Reverse Crunch": "Crunch inversé",
  "Reverse Curl": "Curl inversé",
  "Reverse Curl (Cable)": "Curl inversé (poulie)",
  "Reverse Fly Single Arm (Cable)": "Oiseau un bras (poulie)",
  "Reverse Grip Concentration Curl": "Curl concentré prise inversée",
  "Reverse Grip Lat Pulldown (Cable)": "Tirage vertical supination (poulie)",
  "Reverse Grip Triceps Pushdown": "Extension triceps poulie prise inversée",
  "Reverse Hyperextension": "Hyperextension inversée",
  "Reverse Lunge": "Fente arrière",
  "Reverse Plank": "Planche inversée",
  "Reverse Wrist Curl": "Curl poignets inversé",
  "Ring Dips": "Dips aux anneaux",
  "Ring Pull Up": "Traction aux anneaux",
  "Ring Push Up": "Pompes aux anneaux",
  "Romanian Deadlift": "Soulevé de terre roumain",
  "Romanian Deadlift (Smith Machine)": "Soulevé de terre roumain (Smith)",
  "Rope Cable Curl": "Curl à la corde (poulie)",
  "Rope Straight Arm Pulldown": "Pull-down bras tendus à la corde",
  "Rowing Machine": "Rameur",
  "Running": "Course à pied",
  "Russian Twist (Bodyweight)": "Russian twist (poids du corps)",
  "Russian Twist (Weighted)": "Russian twist (lesté)",
  "Scapular Pull Ups": "Tractions scapulaires",
  "Seal Row": "Seal row",
  "Seated Cable Row": "Rowing assis à la poulie",
  "Seated Cable Row - Bar Grip": "Rowing assis à la poulie (barre)",
  "Seated Cable Row - Bar Wide Grip": "Rowing assis à la poulie (barre, prise large)",
  "Seated Cable Row - V Grip (Cable)": "Rowing assis à la poulie (poignée V)",
  "Seated Calf Raise": "Mollets assis",
  "Seated Chest Flys (Cable)": "Écarté assis (poulie)",
  "Seated Dip (Machine Plate)": "Dips assis (machine à disques)",
  "Seated Dip Machine": "Dips assis (machine)",
  "Seated Dumbbell Press": "Développé assis haltères",
  "Seated Incline Curl": "Curl incliné assis",
  "Seated Incline Curl Life Fitness": "Curl incliné assis (Life Fitness)",
  "Seated Incline Hammer Curl": "Curl marteau incliné assis",
  "Seated Lateral Raise": "Élévation latérale assis",
  "Seated Leg Curl": "Leg curl assis",
  "Seated Overhead Press": "Développé militaire assis",
  "Seated Palms Up Wrist Curl": "Curl poignets assis paumes vers le haut",
  "Seated Row": "Rowing assis",
  "Seated Shoulder Press": "Développé épaules assis",
  "Seated Triceps Press": "Développé triceps assis",
  "Seated Wrist Curl": "Curl poignets assis",
  "Seated Wrist Extension": "Extension des poignets assis",
  "Shoulder Press": "Développé épaules",
  "Shoulder Press (Machine Plates)": "Développé épaules (machine à disques)",
  "Shoulder Taps": "Touches d’épaules",
  "Shrug": "Shrug",
  "Shrug (Cable)": "Shrug (poulie)",
  "Shrug (Smith Machine)": "Shrug (Smith)",
  "Side Bend": "Flexion latérale",
  "Side Plank": "Gainage latéral",
  "Single Arm Bicep Curl (Cable)": "Curl biceps un bras (poulie)",
  "Single Arm Cable Crossover": "Vis-à-vis un bras",
  "Single Arm Cable Row": "Rowing un bras (poulie)",
  "Single Arm Curl (Cable)": "Curl un bras (poulie)",
  "Single Arm Landmine Press": "Développé landmine un bras",
  "Single Arm Lat Pulldown": "Tirage vertical un bras",
  "Single Arm Lateral Raise (Cable)": "Élévation latérale un bras (poulie)",
  "Single Arm Tricep Extension": "Extension triceps un bras",
  "Single Arm Triceps Pushdown (Cable)": "Extension triceps un bras (poulie)",
  "Single Leg Extensions": "Leg extension une jambe",
  "Single Leg Glute Bridge": "Pont fessier une jambe",
  "Single Leg Hip Thrust": "Hip thrust une jambe",
  "Single Leg Press": "Presse à cuisses une jambe",
  "Single Leg Romanian Deadlift": "Soulevé de terre roumain une jambe",
  "Single Leg Standing Calf Raise": "Mollets debout une jambe",
  "Sissy Hack Squat": "Sissy hack squat",
  "Sissy Squat": "Sissy squat",
  "Sissy Squat (Weighted)": "Sissy squat (lesté)",
  "Sit Up": "Relevé de buste",
  "Sit Up (Weighted)": "Relevé de buste (lesté)",
  "Skating": "Patinage",
  "Ski Erg": "SkiErg",
  "Skiing": "Ski",
  "Skull Crusher": "Barre au front",
  "Skullcrusher": "Barre au front",
  "Sled Pull": "Traîneau (tirage)",
  "Sled Push": "Traîneau (poussée)",
  "Snatch": "Arraché",
  "Snowboarding": "Snowboard",
  "Spider Curl": "Spider curl",
  "Spiderman": "Spiderman",
  "Spinning": "Vélo en salle",
  "Split Jerk": "Jeté fendu",
  "Split Squat": "Squat fendu",
  "Sprints": "Sprints",
  "Squat": "Squat",
  "Squat (Band)": "Squat (élastique)",
  "Squat (Bodyweight)": "Squat (poids du corps)",
  "Squat (Smith Machine)": "Squat (Smith)",
  "Squat Row": "Squat rowing",
  "Stair Machine (Floors)": "Simulateur d’escalier (étages)",
  "Stair Machine (Steps)": "Simulateur d’escalier (marches)",
  "Standing Cable Glute Kickbacks": "Kickback fessier debout (poulie)",
  "Standing Calf Raise": "Mollets debout",
  "Standing Calf Raise (Smith)": "Mollets debout (Smith)",
  "Standing Leg Curls": "Leg curl debout",
  "Standing Military Press": "Développé militaire debout",
  "Standing Y Raise (Cable)": "Élévation en Y debout (poulie)",
  "Step Up": "Step-up",
  "Sternum Pull up (Gironda)": "Traction sternum (Gironda)",
  "Stiff-Leg Deadlift": "Soulevé de terre jambes tendues",
  "Straight Arm Lat Pulldown (Cable)": "Pull-down bras tendus (poulie)",
  "Straight Leg Deadlift": "Soulevé de terre jambes tendues",
  "Straight-Arm Pulldown": "Pull-down bras tendus",
  "Stretching": "Étirements",
  "Strong Leg Press Dual (Machine Plate)": "Presse à cuisses double (machine à disques)",
  "Suitcase Carry": "Marche valise",
  "Sumo Deadlift": "Soulevé de terre sumo",
  "Sumo Squat": "Squat sumo",
  "Superman": "Superman",
  "Swimming": "Natation",
  "T Bar Row": "Rowing T-bar",
  "T-Bar Row": "Rowing T-bar",
  "Thruster": "Thruster",
  "Toe Touch": "Toucher d’orteils",
  "Toes to Bar": "Pieds à la barre",
  "Torso Rotation": "Rotation du buste",
  "Trap Bar Deadlift": "Soulevé de terre trap bar",
  "Treadmill": "Tapis de course",
  "Triceps Dip": "Dips triceps",
  "Triceps Dip (Assisted)": "Dips triceps (assisté)",
  "Triceps Dip (Weighted)": "Dips triceps (lesté)",
  "Triceps Extension": "Extension triceps",
  "Triceps Extension (Cable)": "Extension triceps (poulie)",
  "Triceps Kickback": "Kickback triceps",
  "Triceps Kickback (Cable)": "Kickback triceps (poulie)",
  "Triceps Pressdown": "Extension triceps à la poulie",
  "Triceps Pushdown": "Extension triceps à la poulie",
  "Triceps Rope Pushdown": "Extension triceps à la corde",
  "Upright Row": "Rowing menton",
  "Upright Row (Cable)": "Rowing menton (poulie)",
  "UwU Curl": "UwU curl",
  "V Up": "V-up",
  "Vertical Traction": "Traction verticale",
  "Waiter Curl": "Curl serveur",
  "Walking": "Marche",
  "Walking Lunge": "Fentes marchées",
  "Walking Lunge (Sandbag)": "Fentes marchées (sac lesté)",
  "Wall Ball": "Wall ball",
  "Wall Sit": "Chaise",
  "Warm Up": "Échauffement",
  "Wide Pull Up": "Traction prise large",
  "Wide-Elbow Triceps Press": "Développé triceps coudes ouverts",
  "Wrist Curl": "Curl poignets",
  "Wrist Roller": "Rouleau de poignets",
  "Yoga": "Yoga",
  "Zercher Squat": "Squat Zercher",
  "Zottman Curl": "Curl Zottman",
};

/** The name to show, in the app's language. Unknown names come back as given. */
export function exerciseName(name: string, locale: string): string {
  return locale === "fr" ? (FR[name] ?? name) : name;
}

/** Every English name with its French one, for the database pass. */
export const EXERCISE_NAMES_FR = FR;
